apiVersion: v1
kind: Deployment
metadata:
  name: web-deply
  labels:
    app: web
spec:
   replicas:5
   selector:
     matchLabels:
	app:web
spec:
  terminationGracePeriodSeconds:1
  containers:
    - name: hello-pod
      image: dileepchi/k8s:ale
      imgaePullPolicy: Always
      ports:
        - containerPort: 8083